// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TechnicalTestByOrnikar.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("E2ESubcription")]
    [NUnit.Framework.CategoryAttribute("E2ESubcription")]
    public partial class E2ESubcriptionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "E2ESubcription"};
        
#line 1 "E2ESubcription.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "E2ESubcription", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Parcours Souscription Assurance Principale")]
        [NUnit.Framework.TestCaseAttribute("Non", "VOLKSWAGEN", "GOLF IV", "9CV", "ESSENCE", "01-01-2019", "1.8 GTI 150", "01-01-2019", "01-07-2023", "Oui à mon nom", "Depuis plus d\'un an", "Juin", "Au comptant", "01-01-2015", "En France", "Oui", "Pour des trajets privés entre mon domicile et mon travail", "15000", "Dans la rue ou dans un parking public", "75019", "Paris 19", "Un appartement", "Non", "Oui", "Oui, en continu sur toute la période", "1.00, ni bonus, ni malus", "Non", "Non", "Non, aucun", "Non", "John", "Testeur", "M.", "01-01-1991", "Paris", "France", "Salarié", "Je vis seul·e", "randomcryptouser@gmail.com", "0635247146", "5 Rue du Champ de Mars, 75007 Paris, France", "true", null)]
        [NUnit.Framework.TestCaseAttribute("Oui", "RENAULT", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        public void ParcoursSouscriptionAssurancePrincipale(
                    string dejaEnrigistreOption, 
                    string brand, 
                    string model, 
                    string puissanceFiscale, 
                    string carburant, 
                    string dateDeMiseEnCirculation, 
                    string version, 
                    string dateDAchat, 
                    string dateDAsssuranceSouhaite, 
                    string vehiculeDejaAssureOption, 
                    string ancienAssureurDateOption, 
                    string dateDerniereEcheance, 
                    string financementOption, 
                    string dateDuPermis, 
                    string paysPermisDelivre, 
                    string conduiteAccompagneeOption, 
                    string utilisationDuVehiculeOption, 
                    string kmEstime, 
                    string parkingOption, 
                    string postalcode, 
                    string city, 
                    string residenceOption, 
                    string proprietaireResidenceOption, 
                    string carteGriseNomOption, 
                    string dejaAssureOption, 
                    string bonusMalusOption, 
                    string contratResilieOption, 
                    string permisDeConduireEtatOption, 
                    string sinistresOption, 
                    string autreBeneficiaireOption, 
                    string firstname, 
                    string lastname, 
                    string civility, 
                    string birthdate, 
                    string birthcity, 
                    string birthcountry, 
                    string profession, 
                    string statutMarital, 
                    string email, 
                    string mobileNumber, 
                    string adresse, 
                    string newsletterOption, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("déjà enrigistré option", dejaEnrigistreOption);
            argumentsOfScenario.Add("brand", brand);
            argumentsOfScenario.Add("model", model);
            argumentsOfScenario.Add("puissance fiscale", puissanceFiscale);
            argumentsOfScenario.Add("carburant", carburant);
            argumentsOfScenario.Add("date de mise en circulation", dateDeMiseEnCirculation);
            argumentsOfScenario.Add("version", version);
            argumentsOfScenario.Add("date d achat", dateDAchat);
            argumentsOfScenario.Add("date d asssurance souhaité", dateDAsssuranceSouhaite);
            argumentsOfScenario.Add("véhicule déjà assuré option", vehiculeDejaAssureOption);
            argumentsOfScenario.Add("ancien assureur date option", ancienAssureurDateOption);
            argumentsOfScenario.Add("date dernière échéance", dateDerniereEcheance);
            argumentsOfScenario.Add("financement option", financementOption);
            argumentsOfScenario.Add("date du permis", dateDuPermis);
            argumentsOfScenario.Add("pays permis délivré", paysPermisDelivre);
            argumentsOfScenario.Add("conduite accompagnée option", conduiteAccompagneeOption);
            argumentsOfScenario.Add("utilisation du véhicule option", utilisationDuVehiculeOption);
            argumentsOfScenario.Add("km estimé", kmEstime);
            argumentsOfScenario.Add("parking option", parkingOption);
            argumentsOfScenario.Add("postalcode", postalcode);
            argumentsOfScenario.Add("city", city);
            argumentsOfScenario.Add("residence option", residenceOption);
            argumentsOfScenario.Add("propriétaire résidence option", proprietaireResidenceOption);
            argumentsOfScenario.Add("carte grise nom option", carteGriseNomOption);
            argumentsOfScenario.Add("déjà assuré option", dejaAssureOption);
            argumentsOfScenario.Add("bonus malus option", bonusMalusOption);
            argumentsOfScenario.Add("contrat resilié option", contratResilieOption);
            argumentsOfScenario.Add("permis de conduire état option", permisDeConduireEtatOption);
            argumentsOfScenario.Add("sinistres option", sinistresOption);
            argumentsOfScenario.Add("autre bénéficiaire option", autreBeneficiaireOption);
            argumentsOfScenario.Add("firstname", firstname);
            argumentsOfScenario.Add("lastname", lastname);
            argumentsOfScenario.Add("civility", civility);
            argumentsOfScenario.Add("birthdate", birthdate);
            argumentsOfScenario.Add("birthcity", birthcity);
            argumentsOfScenario.Add("birthcountry", birthcountry);
            argumentsOfScenario.Add("profession", profession);
            argumentsOfScenario.Add("statut marital", statutMarital);
            argumentsOfScenario.Add("email", email);
            argumentsOfScenario.Add("mobile number", mobileNumber);
            argumentsOfScenario.Add("adresse", adresse);
            argumentsOfScenario.Add("newsletter option", newsletterOption);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Parcours Souscription Assurance Principale", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
  testRunner.Given("I am on Souscription page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
  testRunner.And(string.Format("I clicked on déjà enrigistré option \"{0}\"", dejaEnrigistreOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 7
  testRunner.When("I click on Rechercher par marque", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 8
  testRunner.Then("I am on search by brand form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 9
  testRunner.And(string.Format("I enter a brand \"{0}\"", brand), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
  testRunner.And("I am on search model form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
  testRunner.And("I click on model list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 12
  testRunner.And(string.Format("I select a model \"{0}\"", model), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 13
  testRunner.And("I am on puissance fiscale form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 14
  testRunner.And(string.Format("I select my puissance fiscale \"{0}\"", puissanceFiscale), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 15
  testRunner.And("I am on carburant/énergie form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 16
  testRunner.And(string.Format("I select my carburant \"{0}\"", carburant), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 17
  testRunner.And("I am on date de mise en circulation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
  testRunner.And(string.Format("I fill date de mise en circulation \"{0}\"", dateDeMiseEnCirculation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
  testRunner.And("I click on Continuer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
  testRunner.And("I am on Quelle est sa version", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
  testRunner.And(string.Format("I select version \"{0}\"", version), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
  testRunner.And("my vehicle is found", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
  testRunner.And("I click on Confirmer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
  testRunner.And("I am on date d\'achat form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
  testRunner.And(string.Format("I fill date d achat \"{0}\"", dateDAchat), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
  testRunner.And("I am on date d\'assurance du véhicule form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 28
  testRunner.And(string.Format("I fill date d asssurance souhaité \"{0}\"", dateDAsssuranceSouhaite), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
  testRunner.And("I am on votre véhicule est-il assuré form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
  testRunner.And(string.Format("I select véhicule déjà assuré option \"{0}\"", vehiculeDejaAssureOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
  testRunner.And("I am on Depuis quand êtes-vous chez votre assureur actuel form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
  testRunner.And(string.Format("I click on ancien assureur date option \"{0}\"", ancienAssureurDateOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
  testRunner.And("I am on Quand votre contrat arrive-t-il à échéance form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
  testRunner.And(string.Format("I select date dernière échéance \"{0}\"", dateDerniereEcheance), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 37
  testRunner.And("I am on Comment l\'avez vous financé form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
  testRunner.And(string.Format("I select financement option \"{0}\"", financementOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 39
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
  testRunner.And("I am on date du permis", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
  testRunner.And(string.Format("I fill date du permis \"{0}\"", dateDuPermis), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
  testRunner.And("I am on où votre premis de conduire a-t-il été délivré form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 44
  testRunner.And(string.Format("I select pays permis délivré \"{0}\"", paysPermisDelivre), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 45
  testRunner.And("I am on Avez-vous fait de la conduite accompagnée form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 46
  testRunner.And(string.Format("I click on conduite accompagnée option \"{0}\"", conduiteAccompagneeOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
  testRunner.And("I am on Dans quel cadre utilisez-vous votre véhicule form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
  testRunner.And(string.Format("I select utilisation du véhicule option \"{0}\"", utilisationDuVehiculeOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
  testRunner.And("I am on combien de kilomètres faites-vous par an form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 50
  testRunner.And(string.Format("I select km estimé \"{0}\"", kmEstime), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
  testRunner.And("I am on Le soir, où sera garé votre véhicule form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
  testRunner.And(string.Format("I select parking option \"{0}\"", parkingOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 54
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
  testRunner.And("I am on Dans quelle ville form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 56
  testRunner.And(string.Format("I fill postalcode \"{0}\"", postalcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 57
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
  testRunner.And("I am on Vous loger dans... form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 59
  testRunner.And(string.Format("I select residence option \"{0}\"", residenceOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 60
  testRunner.And("I am on Êtes-vous propriétaire de votre logement form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 61
  testRunner.And(string.Format("I select propriétaire résidence option \"{0}\"", proprietaireResidenceOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 62
  testRunner.And("I am on La carte grise du véhicule est-elle uniquement à votre nom form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
  testRunner.And(string.Format("I select carte grise nom option \"{0}\"", carteGriseNomOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
  testRunner.And("I am on Avez-vous été assuré", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 65
  testRunner.And(string.Format("I select déjà assuré option \"{0}\"", dejaAssureOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 67
  testRunner.And("I am on Quel est votre bonus malus form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 68
  testRunner.And(string.Format("I select  bonus malus option \"{0}\"", bonusMalusOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 69
  testRunner.And("I click on Continuer button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 70
  testRunner.And("I am on Votre contrat a-t-il été résilié par votre assureur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 71
  testRunner.And(string.Format("I select contrat resilié option \"{0}\"", contratResilieOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 72
  testRunner.And("I am on Votre permis de conduire a-t-il été suspendu ou annulé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
  testRunner.And(string.Format("I select permis de conduire état option \"{0}\"", permisDeConduireEtatOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 74
  testRunner.And("I am on Avez-vous déclaré des sinistres form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 75
  testRunner.And(string.Format("I click on sinistres option \"{0}\"", sinistresOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 76
  testRunner.And("I am on Souhaitez-vous qu\'un autre conducteur bénéficie de vos garanties form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 77
  testRunner.And(string.Format("I select autre bénéficiaire option \"{0}\"", autreBeneficiaireOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 78
  testRunner.And("I am on Informations resumé", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 79
  testRunner.And("the infos displayed are correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 80
  testRunner.And("I click on Confirmer on résumé page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 81
  testRunner.And("I am on il ne vous reste plus qu\'à remplir ces dernières informations form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 82
  testRunner.And(string.Format("I fill firstname \"{0}\" and lastname \"{1}\"", firstname, lastname), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
  testRunner.And(string.Format("I fill civility \"{0}\"", civility), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 84
  testRunner.And(string.Format("I fill birthdate \"{0}\" and birthcity \"{1}\"", birthdate, birthcity), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
  testRunner.And(string.Format("I select birthcountry \"{0}\"", birthcountry), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
  testRunner.And(string.Format("I select profession \"{0}\"", profession), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 87
  testRunner.And(string.Format("I select statut marital \"{0}\"", statutMarital), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 88
  testRunner.And(string.Format("I fill email \"{0}\"", email), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
  testRunner.And(string.Format("I fill mobile number \"{0}\"", mobileNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 90
  testRunner.And(string.Format("I fill adresse \"{0}\"", adresse), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 91
  testRunner.And("I click on J’accepte la politique de confidentialité d’Ornikar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 92
  testRunner.And(string.Format("I click on newsletter option \"{0}\"", newsletterOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 93
  testRunner.And("I click on Obtenir mon tarif", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 94
  testRunner.And("I obtain quotation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
